import sys
from functools import partial

def xxd(variable, file_path):
    """
    Convert binary file into a C-array

    :param str variable:
    :param str file_path:
    :return None:

    """
    print("/* Auto-generated by scripts/xxd.py */")
    print("const unsigned char _CBA_%s[] = {" % variable)
    n = 0
    with open(file_path, "rb") as in_file:
      for c in iter(partial(in_file.read, 1), b''):
        print("0x%02X," % ord(c), end='')
        n += 1
        if n % 16 == 0:
          print("")
    print("};")
    print("const unsigned int _CBA_%s_size = %d;" % (variable, n))

if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit('Usage: %s variable file' % sys.argv[0])
    else:
        xxd(sys.argv[1], sys.argv[2])